/**
 * malla-curricular.ts — Plan de estudios completo de IEK (Ingeniería
 * Electrónica), Semestre 1 a 10, con las 4 orientaciones/énfasis.
 *
 * Extraído y compartido entre /mapa y /poliplanner para no duplicar el
 * plan de estudios en dos lugares. Esta es la malla "oficial" completa
 * (todas las materias que existen en la carrera), independientemente de
 * si se ofertan o no en el período actual — para saber qué se dicta
 * este período y con qué horario, ver src/lib/poliplanner.ts (datos del
 * Excel).
 */
import { HeartPulse, Radio, Settings2, Bot, type LucideIcon } from "lucide-react";
import MALLA_2026_RAW from "@/data/malla-2026.json";

export type EnfasisId =
  "control-industrial" | "electronica-medica" | "mecatronica" | "teleprocesamiento";

export interface EnfasisMeta {
  id: EnfasisId;
  label: string;
  desc: string;
  color: string;
  Icon: LucideIcon;
  gradientStyle: { background: string };
  borderHover: string;
  glowStyle: { boxShadow: string };
}

export const ENFASIS_META: EnfasisMeta[] = [
  {
    id: "control-industrial",
    label: "Control Industrial",
    desc: "Automatización, PLC, sensores, actuadores y sistemas de control de procesos.",
    color: "#3b82f6",
    Icon: Settings2,
    gradientStyle: {
      background: "linear-gradient(135deg, rgba(59,130,246,0.18), rgba(59,130,246,0.06))",
    },
    borderHover: "hover:border-blue-500/50",
    glowStyle: {
      boxShadow: "0 0 0 1px rgba(59,130,246,0.12), 0 20px 60px -20px rgba(59,130,246,0.35)",
    },
  },
  {
    id: "electronica-medica",
    label: "Electrónica Médica",
    desc: "Equipamiento biomédico, instrumentación médica y tecnología sanitaria.",
    color: "#2dd4bf",
    Icon: HeartPulse,
    gradientStyle: {
      background: "linear-gradient(135deg, rgba(45,212,191,0.18), rgba(45,212,191,0.06))",
    },
    borderHover: "hover:border-teal-400/50",
    glowStyle: {
      boxShadow: "0 0 0 1px rgba(45,212,191,0.12), 0 20px 60px -20px rgba(45,212,191,0.35)",
    },
  },
  {
    id: "mecatronica",
    label: "Mecatrónica",
    desc: "Robótica, manufactura, control automático y sistemas mecánicos inteligentes.",
    color: "#a78bfa",
    Icon: Bot,
    gradientStyle: {
      background: "linear-gradient(135deg, rgba(167,139,250,0.18), rgba(167,139,250,0.06))",
    },
    borderHover: "hover:border-violet-400/50",
    glowStyle: {
      boxShadow: "0 0 0 1px rgba(167,139,250,0.12), 0 20px 60px -20px rgba(167,139,250,0.35)",
    },
  },
  {
    id: "teleprocesamiento",
    label: "Teleprocesamiento",
    desc: "Telecomunicaciones, redes de datos, radiofrecuencia y sistemas de transmisión.",
    color: "#fb923c",
    Icon: Radio,
    gradientStyle: {
      background: "linear-gradient(135deg, rgba(251,146,60,0.18), rgba(251,146,60,0.06))",
    },
    borderHover: "hover:border-orange-400/50",
    glowStyle: {
      boxShadow: "0 0 0 1px rgba(251,146,60,0.12), 0 20px 60px -20px rgba(251,146,60,0.35)",
    },
  },
];

/** Alias — en /mapa se usaba este nombre para el mismo array ya decorado. */
export const ENFASIS_OPTIONS = ENFASIS_META;

export const ENFASIS_LABEL: Record<string, string> = Object.fromEntries(
  ENFASIS_META.map((e) => [e.id, e.label]),
);
export const ENFASIS_COLOR: Record<string, string> = Object.fromEntries(
  ENFASIS_META.map((e) => [e.id, e.color]),
);

export interface MateriaMalla {
  id: string;
  nombre: string;
  semestre: number;
  enfasis: (EnfasisId | "comun")[];
  area: string;
  requisitos: string[];
  requisitosEspeciales: string[];
  cargaHoraria: number | null;
}

/** Malla académica aplicable únicamente a estudiantes ingresantes en 2026. */
export const MATERIAS_MALLA_2026: MateriaMalla[] = MALLA_2026_RAW as MateriaMalla[];

export const MATERIAS_MALLA: MateriaMalla[] = [
  {
    id: "algebra",
    nombre: "Álgebra",
    semestre: 1,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "calculo-i",
    nombre: "Cálculo I",
    semestre: 1,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "comunicacion-oral-escrita",
    nombre: "Comunicación Oral y Escrita",
    semestre: 1,
    enfasis: ["comun"],
    area: "Formación General",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "geometria-analitica-vectores",
    nombre: "Geometría Analítica y Vectores",
    semestre: 1,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "desarrollo-emprendedorismo",
    nombre: "Desarrollo del Emprendedorismo",
    semestre: 1,
    enfasis: ["comun"],
    area: "Formación General",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "idioma-i",
    nombre: "Idioma I",
    semestre: 1,
    enfasis: ["comun"],
    area: "Idiomas",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "informatica-aplicada",
    nombre: "Informática Aplicada",
    semestre: 1,
    enfasis: ["comun"],
    area: "Informática",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "dibujo-tecnico",
    nombre: "Dibujo Técnico",
    semestre: 2,
    enfasis: ["comun"],
    area: "Diseño",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "quimica",
    nombre: "Química",
    semestre: 2,
    enfasis: ["comun"],
    area: "Ciencias Básicas",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "calculo-ii",
    nombre: "Cálculo II",
    semestre: 2,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: ["calculo-i", "geometria-analitica-vectores", "algebra"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-i",
    nombre: "Física I",
    semestre: 2,
    enfasis: ["comun"],
    area: "Ciencias Básicas",
    requisitos: ["calculo-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-ii",
    nombre: "Física II",
    semestre: 2,
    enfasis: ["comun"],
    area: "Ciencias Básicas",
    requisitos: ["calculo-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "idioma-ii",
    nombre: "Idioma II",
    semestre: 2,
    enfasis: ["comun"],
    area: "Idiomas",
    requisitos: ["idioma-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "diseno-asistido-computadora",
    nombre: "Diseño Asistido por Computadora",
    semestre: 3,
    enfasis: ["comun"],
    area: "Diseño",
    requisitos: ["dibujo-tecnico"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "calculo-iii",
    nombre: "Cálculo III",
    semestre: 3,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: ["calculo-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "calculo-iv",
    nombre: "Cálculo IV (Vectorial)",
    semestre: 3,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: ["calculo-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "circuitos-electricos-i",
    nombre: "Circuitos Eléctricos I",
    semestre: 3,
    enfasis: ["comun"],
    area: "Electrónica",
    requisitos: ["calculo-ii", "fisica-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-iii",
    nombre: "Física III",
    semestre: 3,
    enfasis: ["comun"],
    area: "Ciencias Básicas",
    requisitos: ["calculo-ii", "fisica-ii", "fisica-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "principios-electronica",
    nombre: "Principios de Electrónica",
    semestre: 3,
    enfasis: ["comun"],
    area: "Electrónica",
    requisitos: ["fisica-ii", "quimica"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "calculo-v",
    nombre: "Cálculo V",
    semestre: 4,
    enfasis: ["comun"],
    area: "Matemática",
    requisitos: ["calculo-iv"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "circuitos-electricos-ii",
    nombre: "Circuitos Eléctricos II",
    semestre: 4,
    enfasis: ["comun"],
    area: "Electrónica",
    requisitos: ["circuitos-electricos-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-i",
    nombre: "Electrónica I",
    semestre: 4,
    enfasis: ["comun"],
    area: "Electrónica",
    requisitos: ["circuitos-electricos-i", "principios-electronica"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-iv",
    nombre: "Física IV",
    semestre: 4,
    enfasis: ["comun"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-iii", "calculo-iv"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-v",
    nombre: "Física V",
    semestre: 4,
    enfasis: ["comun"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-iii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "algoritmo",
    nombre: "Algoritmo",
    semestre: 5,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Informática",
    requisitos: ["calculo-v"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "calculo-vi",
    nombre: "Cálculo VI",
    semestre: 5,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Matemática",
    requisitos: ["calculo-v"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-digital-i",
    nombre: "Electrónica Digital I",
    semestre: 5,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Electrónica",
    requisitos: ["electronica-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-ii",
    nombre: "Electrónica II",
    semestre: 5,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Electrónica",
    requisitos: ["electronica-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "estadistica",
    nombre: "Estadística",
    semestre: 5,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Matemática",
    requisitos: ["calculo-v"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-vi",
    nombre: "Física VI",
    semestre: 5,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-v"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-digital-ii",
    nombre: "Electrónica Digital II",
    semestre: 6,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Electrónica",
    requisitos: ["electronica-digital-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-iii",
    nombre: "Electrónica III",
    semestre: 6,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Electrónica",
    requisitos: ["electronica-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "fisica-vii",
    nombre: "Física VII",
    semestre: 6,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-vi"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "metodologia-investigacion",
    nombre: "Metodología de la Investigación",
    semestre: 6,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Formación General",
    requisitos: ["comunicacion-oral-escrita", "estadistica"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "programacion",
    nombre: "Programación",
    semestre: 6,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Informática",
    requisitos: ["algoritmo"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-control-i",
    nombre: "Sistemas de Control I",
    semestre: 6,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Control",
    requisitos: ["calculo-vi"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "biologia-i",
    nombre: "Biología I",
    semestre: 6,
    enfasis: ["electronica-medica"],
    area: "Ciencias Básicas",
    requisitos: ["quimica", "electronica-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "automatizacion-industrial",
    nombre: "Automatización Industrial",
    semestre: 7,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["electronica-iii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "controladores-programables-i",
    nombre: "Controladores Programables I",
    semestre: 7,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["electronica-digital-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "principios-sensores-actuadores",
    nombre: "Principios de Sensores y Actuadores",
    semestre: 7,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["electronica-iii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-control-ii",
    nombre: "Sistemas de Control II",
    semestre: 7,
    enfasis: ["control-industrial", "teleprocesamiento"],
    area: "Control",
    requisitos: ["sistemas-control-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-digitales-i",
    nombre: "Sistemas Digitales I",
    semestre: 7,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Electrónica",
    requisitos: ["electronica-digital-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-operativos-microcomputadoras",
    nombre: "Sistemas Operativos de Microcomputadoras",
    semestre: 7,
    enfasis: ["control-industrial", "teleprocesamiento"],
    area: "Informática",
    requisitos: ["electronica-digital-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "controladores-programables-ii",
    nombre: "Controladores Programables II",
    semestre: 8,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["controladores-programables-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "instalaciones-electricas-i",
    nombre: "Instalaciones Eléctricas I",
    semestre: 8,
    enfasis: ["control-industrial"],
    area: "Electrónica",
    requisitos: ["automatizacion-industrial"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "instrumentacion-control-industrial",
    nombre: "Instrumentación y Control Industrial",
    semestre: 8,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["principios-sensores-actuadores", "controladores-programables-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "neumatica-hidraulica-industrial",
    nombre: "Neumática e Hidráulica Industrial",
    semestre: 8,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["principios-sensores-actuadores", "controladores-programables-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-potencia-i",
    nombre: "Sistemas de Potencia I",
    semestre: 8,
    enfasis: ["control-industrial"],
    area: "Electrónica",
    requisitos: ["automatizacion-industrial"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-digitales-ii",
    nombre: "Sistemas Digitales II",
    semestre: 8,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Electrónica",
    requisitos: ["sistemas-digitales-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "anteproyecto-trabajo-grado",
    nombre: "Anteproyecto de Trabajo de Grado",
    semestre: 9,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Trabajo de Grado",
    requisitos: [],
    requisitosEspeciales: ["Regular 8vo. Semestre"],
    cargaHoraria: null,
  },
  {
    id: "arquitectura-microcomputadoras",
    nombre: "Arquitectura de Microcomputadoras",
    semestre: 9,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Informática",
    requisitos: ["sistemas-digitales-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "comunicaciones-opticas-ci",
    nombre: "Comunicaciones Ópticas",
    semestre: 9,
    enfasis: ["control-industrial"],
    area: "Telecomunicaciones",
    requisitos: ["sistemas-digitales-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "derecho",
    nombre: "Derecho",
    semestre: 9,
    enfasis: ["control-industrial", "electronica-medica", "mecatronica", "teleprocesamiento"],
    area: "Formación General",
    requisitos: ["metodologia-investigacion"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "instalaciones-electricas-ii",
    nombre: "Instalaciones Eléctricas II",
    semestre: 9,
    enfasis: ["control-industrial"],
    area: "Electrónica",
    requisitos: ["instalaciones-electricas-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-informaticos-automatizacion-control-industrial",
    nombre: "Sistemas Informáticos para Automatización y Control Industrial",
    semestre: 9,
    enfasis: ["control-industrial"],
    area: "Control",
    requisitos: ["controladores-programables-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "administracion-recursos-humanos",
    nombre: "Administración y Recursos Humanos",
    semestre: 10,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Formación General",
    requisitos: ["derecho"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "economia-finanzas",
    nombre: "Economía y Finanzas",
    semestre: 10,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Formación General",
    requisitos: ["anteproyecto-trabajo-grado"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "evaluacion-proyectos",
    nombre: "Evaluación de Proyectos",
    semestre: 10,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Formación General",
    requisitos: ["anteproyecto-trabajo-grado"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "proyecto-trabajo-grado",
    nombre: "Proyecto de Trabajo de Grado",
    semestre: 10,
    enfasis: ["control-industrial", "electronica-medica", "teleprocesamiento"],
    area: "Trabajo de Grado",
    requisitos: ["anteproyecto-trabajo-grado"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "biologia-ii",
    nombre: "Biología II",
    semestre: 7,
    enfasis: ["electronica-medica"],
    area: "Ciencias Básicas",
    requisitos: ["biologia-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-medica-i",
    nombre: "Electrónica Médica I",
    semestre: 7,
    enfasis: ["electronica-medica"],
    area: "Electrónica",
    requisitos: ["biologia-i", "electronica-iii", "electronica-digital-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "mecanica",
    nombre: "Mecánica",
    semestre: 7,
    enfasis: ["electronica-medica"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-vii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "reologia",
    nombre: "Reología",
    semestre: 7,
    enfasis: ["electronica-medica"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-vii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "bioseguridad",
    nombre: "Bioseguridad",
    semestre: 8,
    enfasis: ["electronica-medica"],
    area: "Salud",
    requisitos: ["biologia-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-medica-ii",
    nombre: "Electrónica Médica II",
    semestre: 8,
    enfasis: ["electronica-medica"],
    area: "Electrónica",
    requisitos: ["electronica-medica-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "optica",
    nombre: "Óptica",
    semestre: 8,
    enfasis: ["electronica-medica"],
    area: "Ciencias Básicas",
    requisitos: ["mecanica"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "quimica-clinica-tecnica-laboratorio",
    nombre: "Química Clínica y Técnica de Laboratorio",
    semestre: 8,
    enfasis: ["electronica-medica"],
    area: "Salud",
    requisitos: ["biologia-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "diagnostico-imagenes",
    nombre: "Diagnóstico por Imágenes",
    semestre: 9,
    enfasis: ["electronica-medica"],
    area: "Electrónica",
    requisitos: ["electronica-medica-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-medica-iii",
    nombre: "Electrónica Médica III",
    semestre: 9,
    enfasis: ["electronica-medica"],
    area: "Electrónica",
    requisitos: ["electronica-medica-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "organizacion-hospitalaria",
    nombre: "Organización Hospitalaria",
    semestre: 9,
    enfasis: ["electronica-medica"],
    area: "Salud",
    requisitos: ["electronica-medica-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "modulacion-i",
    nombre: "Modulación I",
    semestre: 7,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["estadistica", "electronica-iii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "protocolos-comunicacion-i",
    nombre: "Protocolos de la Comunicación I",
    semestre: 7,
    enfasis: ["teleprocesamiento"],
    area: "Redes",
    requisitos: ["electronica-digital-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-transmision-recepcion-radio",
    nombre: "Sistemas de Transmisión y Recepción de Radio",
    semestre: 7,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["electronica-iii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "microondas",
    nombre: "Microondas",
    semestre: 8,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["sistemas-transmision-recepcion-radio"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "modulacion-ii",
    nombre: "Modulación II",
    semestre: 8,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["modulacion-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "protocolos-comunicacion-ii",
    nombre: "Protocolos de Comunicación II",
    semestre: 8,
    enfasis: ["teleprocesamiento"],
    area: "Redes",
    requisitos: ["protocolos-comunicacion-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "redes-datos-i",
    nombre: "Redes de Datos I",
    semestre: 8,
    enfasis: ["teleprocesamiento"],
    area: "Redes",
    requisitos: ["protocolos-comunicacion-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistemas-transmision-recepcion-television",
    nombre: "Sistemas de Transmisión y Recepción de Televisión",
    semestre: 8,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["sistemas-transmision-recepcion-radio"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "comunicacion-satelite",
    nombre: "Comunicación por Satélite",
    semestre: 9,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["microondas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "comunicaciones-opticas-ti",
    nombre: "Comunicaciones Ópticas",
    semestre: 9,
    enfasis: ["teleprocesamiento"],
    area: "Telecomunicaciones",
    requisitos: ["microondas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "redes-datos-ii",
    nombre: "Redes de Datos II",
    semestre: 9,
    enfasis: ["teleprocesamiento"],
    area: "Redes",
    requisitos: ["redes-datos-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "dibujo-tecnico-mecanico",
    nombre: "Dibujo Técnico Mecánico",
    semestre: 5,
    enfasis: ["mecatronica"],
    area: "Diseño",
    requisitos: ["dibujo-tecnico"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-aplicada",
    nombre: "Electrónica Aplicada",
    semestre: 5,
    enfasis: ["mecatronica"],
    area: "Electrónica",
    requisitos: ["electronica-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "electronica-digital-meca",
    nombre: "Electrónica Digital",
    semestre: 6,
    enfasis: ["mecatronica"],
    area: "Electrónica",
    requisitos: ["electronica-aplicada"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "maquinas-electricas",
    nombre: "Máquinas Eléctricas",
    semestre: 6,
    enfasis: ["mecatronica"],
    area: "Electrónica",
    requisitos: ["circuitos-electricos-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "mecanica-fluidos",
    nombre: "Mecánica de Fluidos",
    semestre: 6,
    enfasis: ["mecatronica"],
    area: "Ciencias Básicas",
    requisitos: ["fisica-vi"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "principios-metrologia-industrial",
    nombre: "Principios de Metrología Industrial",
    semestre: 6,
    enfasis: ["mecatronica"],
    area: "Control",
    requisitos: ["dibujo-tecnico-mecanico"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "control-automatico-i",
    nombre: "Control Automático I",
    semestre: 7,
    enfasis: ["mecatronica"],
    area: "Control",
    requisitos: ["maquinas-electricas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "diseno-elementos-maquinas",
    nombre: "Diseño de Elementos de Máquinas",
    semestre: 7,
    enfasis: ["mecatronica"],
    area: "Diseño",
    requisitos: [],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "elementos-maquinas",
    nombre: "Elementos de Máquinas",
    semestre: 7,
    enfasis: ["mecatronica"],
    area: "Mecánica",
    requisitos: ["fisica-vi"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "metodos-elementos-finitos",
    nombre: "Métodos de los Elementos Finitos",
    semestre: 7,
    enfasis: ["mecatronica"],
    area: "Mecánica",
    requisitos: ["fisica-vi"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "microcontroladores",
    nombre: "Microcontroladores",
    semestre: 7,
    enfasis: ["mecatronica"],
    area: "Electrónica",
    requisitos: ["electronica-digital-meca"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "modelado-sistemas-fisicos",
    nombre: "Modelado de Sistemas Físicos",
    semestre: 7,
    enfasis: ["mecatronica"],
    area: "Control",
    requisitos: ["mecanica-fluidos"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "control-automatico-ii",
    nombre: "Control Automático II",
    semestre: 8,
    enfasis: ["mecatronica"],
    area: "Control",
    requisitos: ["control-automatico-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "diseno-manufactura-asistida-computadora",
    nombre: "Diseño y Manufactura Asistido por Computadora",
    semestre: 8,
    enfasis: ["mecatronica"],
    area: "Manufactura",
    requisitos: ["diseno-elementos-maquinas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "manufactura-maquinas-convencionales",
    nombre: "Manufactura con Máquinas Convencionales",
    semestre: 8,
    enfasis: ["mecatronica"],
    area: "Manufactura",
    requisitos: ["elementos-maquinas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "maquinas-control-numerico-computarizado",
    nombre: "Máquinas a Control Numérico Computarizado",
    semestre: 8,
    enfasis: ["mecatronica"],
    area: "Manufactura",
    requisitos: ["diseno-elementos-maquinas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "proyectos-sistemas-mecatronicos-i",
    nombre: "Proyectos de Sistemas Mecatrónicos I",
    semestre: 8,
    enfasis: ["mecatronica"],
    area: "Mecatrónica",
    requisitos: ["microcontroladores", "diseno-elementos-maquinas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "robotica",
    nombre: "Robótica",
    semestre: 8,
    enfasis: ["mecatronica"],
    area: "Mecatrónica",
    requisitos: ["microcontroladores"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "control-avanzado",
    nombre: "Control Avanzado",
    semestre: 9,
    enfasis: ["mecatronica"],
    area: "Control",
    requisitos: ["control-automatico-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "inteligencia-artificial",
    nombre: "Inteligencia Artificial",
    semestre: 9,
    enfasis: ["mecatronica"],
    area: "Informática",
    requisitos: ["robotica"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "proyectos-sistemas-mecatronicos-ii",
    nombre: "Proyectos de Sistemas Mecatrónicos II",
    semestre: 9,
    enfasis: ["mecatronica"],
    area: "Mecatrónica",
    requisitos: ["proyectos-sistemas-mecatronicos-i"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "simulacion-sistemas-dinamicos",
    nombre: "Simulación de Sistemas Dinámicos",
    semestre: 9,
    enfasis: ["mecatronica"],
    area: "Control",
    requisitos: ["diseno-elementos-maquinas"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistema-manufactura-flexible",
    nombre: "Sistema de Manufactura Flexible",
    semestre: 9,
    enfasis: ["mecatronica"],
    area: "Manufactura",
    requisitos: ["robotica", "maquinas-control-numerico-computarizado"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "economia-finanzas-meca",
    nombre: "Economía y Finanzas",
    semestre: 10,
    enfasis: ["mecatronica"],
    area: "Formación General",
    requisitos: ["estadistica", "proyectos-sistemas-mecatronicos-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "ingenieria-materiales",
    nombre: "Ingeniería de Materiales",
    semestre: 10,
    enfasis: ["mecatronica"],
    area: "Mecánica",
    requisitos: ["metodos-elementos-finitos", "manufactura-maquinas-convencionales"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "planeamiento-control-produccion",
    nombre: "Planeamiento y Control de la Producción",
    semestre: 10,
    enfasis: ["mecatronica"],
    area: "Manufactura",
    requisitos: ["control-avanzado", "estadistica"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "proyecto-trabajo-grado-meca",
    nombre: "Proyecto de Trabajo de Grado",
    semestre: 10,
    enfasis: ["mecatronica"],
    area: "Trabajo de Grado",
    requisitos: ["proyectos-sistemas-mecatronicos-ii"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
  {
    id: "sistema-mejoramiento-ambiental",
    nombre: "Sistema de Mejoramiento Ambiental",
    semestre: 10,
    enfasis: ["mecatronica"],
    area: "Formación General",
    requisitos: ["derecho"],
    requisitosEspeciales: [],
    cargaHoraria: null,
  },
];

export const MALLAS_ACADEMICAS = {
  "plan-2008": MATERIAS_MALLA,
  "vigente-2026": MATERIAS_MALLA_2026,
} as const;

export type MallaAcademicaId = keyof typeof MALLAS_ACADEMICAS;

/** Materias de Plan Básico (comunes a todos los énfasis) + las propias de un énfasis, ordenadas por semestre. */
export function mallaPorEnfasis(enfasis: EnfasisId): MateriaMalla[] {
  return MATERIAS_MALLA.filter(
    (m) => m.enfasis.includes("comun") || m.enfasis.includes(enfasis),
  ).sort((a, b) => a.semestre - b.semestre || a.nombre.localeCompare(b.nombre, "es"));
}

export function mallaAgrupadaPorSemestre(
  enfasis: EnfasisId,
): { semestre: number; materias: MateriaMalla[] }[] {
  const materias = mallaPorEnfasis(enfasis);
  const map = new Map<number, MateriaMalla[]>();
  materias.forEach((m) => {
    if (!map.has(m.semestre)) map.set(m.semestre, []);
    map.get(m.semestre)!.push(m);
  });
  return [...map.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([semestre, materias]) => ({ semestre, materias }));
}
