/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as Reglamento2026RouteImport } from './routes/reglamento-2026'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as RadarAcademicoRouteImport } from './routes/radar-academico'
import { Route as PromedioRouteImport } from './routes/promedio'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PoliplannerRouteImport } from './routes/poliplanner'
import { Route as PlanDeEstudioRouteImport } from './routes/plan-de-estudio'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ManualDeBichosRouteImport } from './routes/manual-de-bichos'
import { Route as Laboratorio000RouteImport } from './routes/laboratorio-000'
import { Route as GeneradorSemestreRouteImport } from './routes/generador-semestre'
import { Route as DelegacionRouteImport } from './routes/delegacion'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CarreraRouteImport } from './routes/carrera'
import { Route as CalendarioAcademicoRouteImport } from './routes/calendario-academico'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const Reglamento2026Route = Reglamento2026RouteImport.update({
  id: '/reglamento-2026',
  path: '/reglamento-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarAcademicoRoute = RadarAcademicoRouteImport.update({
  id: '/radar-academico',
  path: '/radar-academico',
  getParentRoute: () => rootRouteImport,
} as any)
const PromedioRoute = PromedioRouteImport.update({
  id: '/promedio',
  path: '/promedio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliplannerRoute = PoliplannerRouteImport.update({
  id: '/poliplanner',
  path: '/poliplanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDeEstudioRoute = PlanDeEstudioRouteImport.update({
  id: '/plan-de-estudio',
  path: '/plan-de-estudio',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualDeBichosRoute = ManualDeBichosRouteImport.update({
  id: '/manual-de-bichos',
  path: '/manual-de-bichos',
  getParentRoute: () => rootRouteImport,
} as any)
const Laboratorio000Route = Laboratorio000RouteImport.update({
  id: '/laboratorio-000',
  path: '/laboratorio-000',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneradorSemestreRoute = GeneradorSemestreRouteImport.update({
  id: '/generador-semestre',
  path: '/generador-semestre',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegacionRoute = DelegacionRouteImport.update({
  id: '/delegacion',
  path: '/delegacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreraRoute = CarreraRouteImport.update({
  id: '/carrera',
  path: '/carrera',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioAcademicoRoute = CalendarioAcademicoRouteImport.update({
  id: '/calendario-academico',
  path: '/calendario-academico',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistencia': typeof AsistenciaRoute
  '/aulas': typeof AulasRoute
  '/avisos': typeof AvisosRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario-academico': typeof CalendarioAcademicoRoute
  '/carrera': typeof CarreraRoute
  '/contacto': typeof ContactoRoute
  '/cuenta': typeof CuentaRoute
  '/delegacion': typeof DelegacionRoute
  '/generador-semestre': typeof GeneradorSemestreRoute
  '/laboratorio-000': typeof Laboratorio000Route
  '/manual-de-bichos': typeof ManualDeBichosRoute
  '/mapa': typeof MapaRoute
  '/plan-de-estudio': typeof PlanDeEstudioRoute
  '/poliplanner': typeof PoliplannerRoute
  '/privacidad': typeof PrivacidadRoute
  '/promedio': typeof PromedioRoute
  '/radar-academico': typeof RadarAcademicoRoute
  '/recursos': typeof RecursosRoute
  '/reglamento-2026': typeof Reglamento2026Route
  '/terminos': typeof TerminosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistencia': typeof AsistenciaRoute
  '/aulas': typeof AulasRoute
  '/avisos': typeof AvisosRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario-academico': typeof CalendarioAcademicoRoute
  '/carrera': typeof CarreraRoute
  '/contacto': typeof ContactoRoute
  '/cuenta': typeof CuentaRoute
  '/delegacion': typeof DelegacionRoute
  '/generador-semestre': typeof GeneradorSemestreRoute
  '/laboratorio-000': typeof Laboratorio000Route
  '/manual-de-bichos': typeof ManualDeBichosRoute
  '/mapa': typeof MapaRoute
  '/plan-de-estudio': typeof PlanDeEstudioRoute
  '/poliplanner': typeof PoliplannerRoute
  '/privacidad': typeof PrivacidadRoute
  '/promedio': typeof PromedioRoute
  '/radar-academico': typeof RadarAcademicoRoute
  '/recursos': typeof RecursosRoute
  '/reglamento-2026': typeof Reglamento2026Route
  '/terminos': typeof TerminosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/asistencia': typeof AsistenciaRoute
  '/aulas': typeof AulasRoute
  '/avisos': typeof AvisosRoute
  '/calculadora': typeof CalculadoraRoute
  '/calendario-academico': typeof CalendarioAcademicoRoute
  '/carrera': typeof CarreraRoute
  '/contacto': typeof ContactoRoute
  '/cuenta': typeof CuentaRoute
  '/delegacion': typeof DelegacionRoute
  '/generador-semestre': typeof GeneradorSemestreRoute
  '/laboratorio-000': typeof Laboratorio000Route
  '/manual-de-bichos': typeof ManualDeBichosRoute
  '/mapa': typeof MapaRoute
  '/plan-de-estudio': typeof PlanDeEstudioRoute
  '/poliplanner': typeof PoliplannerRoute
  '/privacidad': typeof PrivacidadRoute
  '/promedio': typeof PromedioRoute
  '/radar-academico': typeof RadarAcademicoRoute
  '/recursos': typeof RecursosRoute
  '/reglamento-2026': typeof Reglamento2026Route
  '/terminos': typeof TerminosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/asistencia'
    | '/aulas'
    | '/avisos'
    | '/calculadora'
    | '/calendario-academico'
    | '/carrera'
    | '/contacto'
    | '/cuenta'
    | '/delegacion'
    | '/generador-semestre'
    | '/laboratorio-000'
    | '/manual-de-bichos'
    | '/mapa'
    | '/plan-de-estudio'
    | '/poliplanner'
    | '/privacidad'
    | '/promedio'
    | '/radar-academico'
    | '/recursos'
    | '/reglamento-2026'
    | '/terminos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/asistencia'
    | '/aulas'
    | '/avisos'
    | '/calculadora'
    | '/calendario-academico'
    | '/carrera'
    | '/contacto'
    | '/cuenta'
    | '/delegacion'
    | '/generador-semestre'
    | '/laboratorio-000'
    | '/manual-de-bichos'
    | '/mapa'
    | '/plan-de-estudio'
    | '/poliplanner'
    | '/privacidad'
    | '/promedio'
    | '/radar-academico'
    | '/recursos'
    | '/reglamento-2026'
    | '/terminos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/asistencia'
    | '/aulas'
    | '/avisos'
    | '/calculadora'
    | '/calendario-academico'
    | '/carrera'
    | '/contacto'
    | '/cuenta'
    | '/delegacion'
    | '/generador-semestre'
    | '/laboratorio-000'
    | '/manual-de-bichos'
    | '/mapa'
    | '/plan-de-estudio'
    | '/poliplanner'
    | '/privacidad'
    | '/promedio'
    | '/radar-academico'
    | '/recursos'
    | '/reglamento-2026'
    | '/terminos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AsistenciaRoute: typeof AsistenciaRoute
  AulasRoute: typeof AulasRoute
  AvisosRoute: typeof AvisosRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CalendarioAcademicoRoute: typeof CalendarioAcademicoRoute
  CarreraRoute: typeof CarreraRoute
  ContactoRoute: typeof ContactoRoute
  CuentaRoute: typeof CuentaRoute
  DelegacionRoute: typeof DelegacionRoute
  GeneradorSemestreRoute: typeof GeneradorSemestreRoute
  Laboratorio000Route: typeof Laboratorio000Route
  ManualDeBichosRoute: typeof ManualDeBichosRoute
  MapaRoute: typeof MapaRoute
  PlanDeEstudioRoute: typeof PlanDeEstudioRoute
  PoliplannerRoute: typeof PoliplannerRoute
  PrivacidadRoute: typeof PrivacidadRoute
  PromedioRoute: typeof PromedioRoute
  RadarAcademicoRoute: typeof RadarAcademicoRoute
  RecursosRoute: typeof RecursosRoute
  Reglamento2026Route: typeof Reglamento2026Route
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglamento-2026': {
      id: '/reglamento-2026'
      path: '/reglamento-2026'
      fullPath: '/reglamento-2026'
      preLoaderRoute: typeof Reglamento2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar-academico': {
      id: '/radar-academico'
      path: '/radar-academico'
      fullPath: '/radar-academico'
      preLoaderRoute: typeof RadarAcademicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promedio': {
      id: '/promedio'
      path: '/promedio'
      fullPath: '/promedio'
      preLoaderRoute: typeof PromedioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poliplanner': {
      id: '/poliplanner'
      path: '/poliplanner'
      fullPath: '/poliplanner'
      preLoaderRoute: typeof PoliplannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-de-estudio': {
      id: '/plan-de-estudio'
      path: '/plan-de-estudio'
      fullPath: '/plan-de-estudio'
      preLoaderRoute: typeof PlanDeEstudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-de-bichos': {
      id: '/manual-de-bichos'
      path: '/manual-de-bichos'
      fullPath: '/manual-de-bichos'
      preLoaderRoute: typeof ManualDeBichosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratorio-000': {
      id: '/laboratorio-000'
      path: '/laboratorio-000'
      fullPath: '/laboratorio-000'
      preLoaderRoute: typeof Laboratorio000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generador-semestre': {
      id: '/generador-semestre'
      path: '/generador-semestre'
      fullPath: '/generador-semestre'
      preLoaderRoute: typeof GeneradorSemestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegacion': {
      id: '/delegacion'
      path: '/delegacion'
      fullPath: '/delegacion'
      preLoaderRoute: typeof DelegacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrera': {
      id: '/carrera'
      path: '/carrera'
      fullPath: '/carrera'
      preLoaderRoute: typeof CarreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario-academico': {
      id: '/calendario-academico'
      path: '/calendario-academico'
      fullPath: '/calendario-academico'
      preLoaderRoute: typeof CalendarioAcademicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AsistenciaRoute: AsistenciaRoute,
  AulasRoute: AulasRoute,
  AvisosRoute: AvisosRoute,
  CalculadoraRoute: CalculadoraRoute,
  CalendarioAcademicoRoute: CalendarioAcademicoRoute,
  CarreraRoute: CarreraRoute,
  ContactoRoute: ContactoRoute,
  CuentaRoute: CuentaRoute,
  DelegacionRoute: DelegacionRoute,
  GeneradorSemestreRoute: GeneradorSemestreRoute,
  Laboratorio000Route: Laboratorio000Route,
  ManualDeBichosRoute: ManualDeBichosRoute,
  MapaRoute: MapaRoute,
  PlanDeEstudioRoute: PlanDeEstudioRoute,
  PoliplannerRoute: PoliplannerRoute,
  PrivacidadRoute: PrivacidadRoute,
  PromedioRoute: PromedioRoute,
  RadarAcademicoRoute: RadarAcademicoRoute,
  RecursosRoute: RecursosRoute,
  Reglamento2026Route: Reglamento2026Route,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
